name: refena_flutter
description: A state management library for Dart and Flutter. Inspired by Riverpod and async_redux.
version: 0.39.0
repository: https://github.com/refena/refena/tree/main/refena_flutter
issue_tracker: https://github.com/refena/refena/issues
topics:
  - state
  - provider
  - riverpod
  - framework
  - redux
screenshots:
  - description: The Refena logo.
    path: resources/icon.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.0
  refena: ^0.39.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
