name: refena_inspector
description: The inspector developer utility app for the Refena state management library.
version: 2.0.2
repository: https://github.com/refena/refena/tree/main/refena_inspector
issue_tracker: https://github.com/refena/refena/issues
topics:
  - refena
screenshots:
  - description: The Refena logo.
    path: resources/icon.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.17.0 <1.0.0'
  logging: ^1.1.0
  path: ^1.8.0
  refena: ^2.0.0
  refena_flutter: ^2.0.0

  # Use a tight version to ensure that all features are available
  refena_inspector_client: '>=2.0.0 <2.1.0'

  shelf: ^1.4.1
  shelf_web_socket: '>=1.0.4 <3.0.0'
  web_socket_channel: '>= 2.4.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
