name: refena
description: A state management library for Dart and Flutter. Inspired by Riverpod and async_redux.
version: 1.0.0
repository: https://github.com/refena/refena/tree/main/refena
issue_tracker: https://github.com/refena/refena/issues
topics:
  - state
  - provider
  - riverpod
  - framework
  - redux
screenshots:
  - description: The Refena logo.
    path: resources/icon.png
funding:
  - https://github.com/sponsors/Tienisto/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.6
